const categories = [
  {
    label: 'General Knowledge',
    subCategories: [
      'General Knowledge: General',
      'General Knowledge: Pub Quiz',
      'General Knowledge: World Facts & Figures',
      'General Knowledge: Common Sayings & Proverbs (Global)',
      'General Knowledge: Cultural Trivia',
      'General Knowledge: Random Fun Facts',
    ],
  },
  {
    label: 'Pop Culture',
    subCategories: [
      'Pop Culture: General',
      'Pop Culture: 1960s-70s Icons',
      'Pop Culture: 1980s Culture',
      'Pop Culture: 1990s Nostalgia',
      'Pop Culture: 2000s Trends',
      'Pop Culture: 2010s Culture',
      'Pop Culture: Current Trends (2020s)',
      'Pop Culture: Celebrities & Gossip',
      'Pop Culture: Social Media & Internet Culture',
      'Pop Culture: Viral Videos & Memes',
      'Pop Culture: Fashion & Style Through Decades',
    ],
  },
  {
    label: 'Movies',
    subCategories: [
      'Movies: General',
      'Movies: Classic Hollywood (1930s-60s)',
      'Movies: 1970s-80s Blockbusters',
      'Movies: 1990s Cinema',
      'Movies: 2000s Films',
      'Movies: Modern Movies (2010s-2020s)',
      'Movies: International Cinema (Bollywood, European, Asian)',
      'Movies: Action & Adventure',
      'Movies: Comedy',
      'Movies: Drama',
      'Movies: Horror',
      'Movies: Sci-Fi & Fantasy',
      'Movies: Animated Films',
      'Movies: Movie Quotes',
      'Movies: Actors & Actresses',
      'Movies: Directors',
      'Movies: Award Winners (Oscars, Golden Globes, etc.)',
    ],
  },
  {
    label: 'TV Shows',
    subCategories: [
      'TV Shows: General',
      'TV Shows: Classic TV (1950s-80s)',
      'TV Shows: 1990s Television',
      'TV Shows: 2000s Shows',
      'TV Shows: Modern TV (2010s-2020s)',
      'TV Shows: International Shows (K-dramas, British, etc.)',
      'TV Shows: Sitcoms',
      'TV Shows: Dramas',
      'TV Shows: Reality TV',
      'TV Shows: Game Shows',
      'TV Shows: Cartoons & Animation',
      'TV Shows: Streaming Originals (Netflix, HBO, Disney+, etc.)',
      'TV Shows: TV Quotes',
      'TV Shows: TV Characters',
      'TV Shows: Award Winners (Emmys, etc.)',
    ],
  },
  {
    label: 'Music',
    subCategories: [
      'Music: General',
      'Music: By Decade: 1950s-60s Classics',
      'Music: By Decade: 70s',
      'Music: By Decade: 80s',
      'Music: By Decade: 90s',
      'Music: By Decade: 00s',
      'Music: By Decade: 2010s',
      'Music: By Decade: Current Hits',
      'Music: By Genre: Pop',
      'Music: By Genre: Rock',
      'Music: By Genre: Hip Hop',
      'Music: By Genre: R&B',
      'Music: By Genre: Country',
      'Music: By Genre: Classical',
      'Music: By Genre: Jazz',
      'Music: By Genre: Electronic',
      'Music: By Genre: World Music (Latin, African, Asian, etc.)',
      'Music: Artists & Bands',
      'Music: Song Lyrics',
      'Music: Albums',
      'Music: Award Winners (Grammys, etc.)',
    ],
  },
  {
    label: 'Books / Literature',
    subCategories: [
      'Books / Literature: General',
      'Books / Literature: Classic Novels',
      'Books / Literature: Modern Fiction',
      'Books / Literature: World Literature (Non-Western)',
      'Books / Literature: Poetry',
      'Books / Literature: Children\'s Literature',
      'Books / Literature: Fantasy & Sci-Fi Books',
      'Books / Literature: Authors',
      'Books / Literature: Book Characters',
      'Books / Literature: Literary Quotes',
    ],
  },
  {
    label: 'Video Games',
    subCategories: [
      'Video Games: General',
      'Video Games: Retro Games (1970s-90s)',
      'Video Games: 2000s Gaming',
      'Video Games: Modern Gaming (2010s-2020s)',
      'Video Games: Console Games (PlayStation, Xbox, Nintendo)',
      'Video Games: PC Games',
      'Video Games: Mobile Games',
      'Video Games: Game Characters',
      'Video Games: Game Developers',
      'Video Games: Esports',
      'Video Games: Game Soundtracks',
    ],
  },
  {
    label: 'Sports',
    subCategories: [
      'Sports: General',
      'Sports: By Sport: Football (Soccer)',
      'Sports: By Sport: American Football',
      'Sports: By Sport: Basketball',
      'Sports: By Sport: Baseball',
      'Sports: By Sport: Tennis',
      'Sports: By Sport: Golf',
      'Sports: By Sport: Hockey',
      'Sports: By Sport: Cricket',
      'Sports: By Sport: Rugby',
      'Sports: By Sport: Athletics (Track & Field)',
      'Sports: By Sport: Swimming',
      'Sports: By Sport: Motorsports',
      'Sports: Olympics',
      'Sports: World Cups / Championships',
      'Sports: Famous Athletes',
      'Sports: Team Nicknames',
      'Sports: Sports History',
    ],
  },
  {
    label: 'History',
    subCategories: [
      'History: General',
      'History: Ancient History',
      'History: Medieval History',
      'History: Modern History',
      'History: World Wars',
      'History: American History',
      'History: European History',
      'History: Asian History',
      'History: African History',
      'History: Latin American History',
      'History: Famous Historical Figures',
      'History: Historical Events',
      'History: Inventions & Discoveries',
    ],
  },
  {
    label: 'Geography',
    subCategories: [
      'Geography: General',
      'Geography: Countries & Capitals',
      'Geography: Continents & Oceans',
      'Geography: Mountains & Rivers',
      'Geography: Cities & Landmarks',
      'Geography: Flags of the World',
      'Geography: World Wonders',
      'Geography: UNESCO World Heritage Sites',
    ],
  },
  {
    label: 'Science',
    subCategories: [
      'Science: General',
      'Science: Biology',
      'Science: Chemistry',
      'Science: Physics',
      'Science: Astronomy & Space',
      'Science: Geology',
      'Science: Environmental Science',
      'Science: Inventions & Discoveries',
      'Science: Human Body & Medicine',
      'Science: Famous Scientists',
    ],
  },
  {
    label: 'Art & Literature',
    subCategories: [
      'Art & Literature: General',
      'Art & Literature: Art: Famous Paintings',
      'Art & Literature: Art: Sculptures',
      'Art & Literature: Art: Artists (Western)',
      'Art & Literature: Art: Artists (Non-Western)',
      'Art & Literature: Art: Art Movements',
      'Art & Literature: Literature: Genres',
      'Art & Literature: Literature: Authors',
      'Art & Literature: Literature: Literary Devices',
      'Art & Literature: Literature: Famous Books',
    ],
  },
  {
    label: 'Food & Drink',
    subCategories: [
      'Food & Drink: General',
      'Food & Drink: Asian Cuisine',
      'Food & Drink: European Cuisine',
      'Food & Drink: Latin American Cuisine',
      'Food & Drink: African Cuisine',
      'Food & Drink: Middle Eastern Cuisine',
      'Food & Drink: North American Cuisine',
      'Food & Drink: Beverages (Coffee, Tea, Alcoholic Drinks)',
      'Food & Drink: Desserts',
      'Food & Drink: Cooking & Culinary Terms',
    ],
  },
  {
    label: 'Animals',
    subCategories: [
      'Animals: General',
      'Animals: African Wildlife',
      'Animals: Asian Wildlife',
      'Animals: North American Wildlife',
      'Animals: South American Wildlife',
      'Animals: European Wildlife',
      'Animals: Australian & Oceanic Wildlife',
      'Animals: Marine Life',
      'Animals: Birds',
      'Animals: Mammals',
      'Animals: Reptiles',
      'Animals: Amphibians',
      'Animals: Fish',
      'Animals: Insects & Arachnids',
      'Animals: Domestic Animals (Cats, Dogs, Horses)',
      'Animals: Animal Behavior',
    ],
  },
  {
    label: 'Mythology',
    subCategories: [
      'Mythology: General',
      'Mythology: Greek Mythology',
      'Mythology: Roman Mythology',
      'Mythology: Norse Mythology',
      'Mythology: Egyptian Mythology',
      'Mythology: Asian Mythology (Chinese, Japanese, Indian)',
      'Mythology: Native American Folklore',
      'Mythology: African Folklore',
      'Mythology: Celtic Mythology',
      'Mythology: Mythical Creatures',
    ],
  },
  {
    label: 'Technology',
    subCategories: [
      'Technology: General',
      'Technology: Computers & Software',
      'Technology: Internet & Web',
      'Technology: Gadgets & Devices',
      'Technology: Programming Languages',
      'Technology: Social Media Platforms',
      'Technology: Artificial Intelligence',
      'Technology: Robotics',
      'Technology: Space Technology',
    ],
  },
  {
    label: 'Current Events',
    subCategories: [
      'Current Events: General',
      'Current Events: News (Recent Headlines)',
      'Current Events: Politics (Recent Events)',
      'Current Events: Major Global Developments',
      'Current Events: Environmental Issues',
      'Current Events: Social Movements',
    ],
  },
  {
    label: 'Holidays',
    subCategories: [
      'Holidays: General',
      'Holidays: Christmas',
      'Holidays: Halloween',
      'Holidays: Thanksgiving',
      'Holidays: Valentine\'s Day',
      'Holidays: Easter',
      'Holidays: New Year Traditions (Global)',
      'Holidays: Religious Celebrations',
      'Holidays: Cultural Festivals',
    ],
  },
  {
    label: 'Language & Words',
    subCategories: [
      'Language & Words: General',
      'Language & Words: English Language',
      'Language & Words: Spanish Language',
      'Language & Words: French Language',
      'Language & Words: Other World Languages',
      'Language & Words: Vocabulary',
      'Language & Words: Etymology',
      'Language & Words: Grammar',
      'Language & Words: Foreign Words/Phrases',
    ],
  },
]

export default categories
