const categories = [
  {
    label: 'General Knowledge',
    subCategories: [
      'General Knowledge: General',
      'General Knowledge: Facts & Figures',
      'General Knowledge: Common Sayings & Idioms',
    ],
  },
  {
    label: 'Pop Culture',
    subCategories: [
      'Pop Culture: General',
      'Pop Culture: Celebrities & Gossip',
      'Pop Culture: Trends & Fads',
      'Pop Culture: Social Media & Internet Culture',
      'Pop Culture: Viral Videos & Memes',
    ],
  },
  {
    label: 'Movies',
    subCategories: [
      'Movies: General',
      'Movies: Blockbusters',
      'Movies: Action & Adventure',
      'Movies: Comedy',
      'Movies: Drama',
      'Movies: Horror',
      'Movies: Sci-Fi & Fantasy',
      'Movies: Animated Films',
      'Movies: Movie Quotes',
      'Movies: Actors & Actresses',
      'Movies: Directors',
      'Movies: Award Winners (Oscars, Golden Globes, etc.)',
    ],
  },
  {
    label: 'TV Shows',
    subCategories: [
      'TV Shows: General',
      'TV Shows: Sitcoms',
      'TV Shows: Dramas',
      'TV Shows: Reality TV',
      'TV Shows: Game Shows',
      'TV Shows: Cartoons & Animation',
      'TV Shows: Streaming Originals (Netflix, HBO, Disney+, etc.)',
      'TV Shows: TV Quotes',
      'TV Shows: TV Characters',
      'TV Shows: Award Winners (Emmys, etc.)',
    ],
  },
  {
    label: 'Music',
    subCategories: [
      'Music: General',
      'Music: By Decade: 70s',
      'Music: By Decade: 80s',
      'Music: By Decade: 90s',
      'Music: By Decade: 00s',
      'Music: By Decade: 2010s',
      'Music: By Decade: Current Hits',
      'Music: By Genre: Pop',
      'Music: By Genre: Rock',
      'Music: By Genre: Hip Hop',
      'Music: By Genre: R&B',
      'Music: By Genre: Country',
      'Music: By Genre: Classical',
      'Music: By Genre: Jazz',
      'Music: By Genre: Electronic',
      'Music: By Genre: Indie',
      'Music: Artists & Bands',
      'Music: Song Lyrics',
      'Music: Albums',
      'Music: Award Winners (Grammys, etc.)',
    ],
  },
  {
    label: 'Books / Literature',
    subCategories: [
      'Books / Literature: General',
      'Books / Literature: Classic Novels',
      'Books / Literature: Modern Fiction',
      'Books / Literature: Poetry',
      'Books / Literature: Children"s Literature',
      'Books / Literature: Fantasy & Sci-Fi Books',
      'Books / Literature: Authors',
      'Books / Literature: Book Characters',
      'Books / Literature: Literary Quotes',
    ],
  },
  {
    label: 'Video Games',
    subCategories: [
      'Video Games: General',
      'Video Games: Console Games (PlayStation, Xbox, Nintendo)',
      'Video Games: PC Games',
      'Video Games: Mobile Games',
      'Video Games: Retro Games',
      'Video Games: Game Characters',
      'Video Games: Game Developers',
      'Video Games: Esports',
      'Video Games: Game Soundtracks',
    ],
  },
  {
    label: 'Sports',
    subCategories: [
      'Sports: General',
      'Sports: By Sport: Football (Soccer)',
      'Sports: By Sport: American Football',
      'Sports: By Sport: Basketball',
      'Sports: By Sport: Baseball',
      'Sports: By Sport: Tennis',
      'Sports: By Sport: Golf',
      'Sports: By Sport: Hockey',
      'Sports: By Sport: Athletics (Track & Field)',
      'Sports: By Sport: Swimming',
      'Sports: By Sport: Motorsports',
      'Sports: Olympics',
      'Sports: World Cups / Championships',
      'Sports: Famous Athletes',
      'Sports: Team Nicknames',
      'Sports: Sports History',
    ],
  },
  {
    label: 'History',
    subCategories: [
      'History: General',
      'History: Ancient History',
      'History: Medieval History',
      'History: Modern History',
      'History: World Wars',
      'History: Famous Historical Figures',
      'History: Historical Events',
      'History: American History (or specific country history)',
      'History: Inventions & Discoveries',
    ],
  },
  {
    label: 'Geography',
    subCategories: [
      'Geography: General',
      'Geography: Countries & Capitals',
      'Geography: Continents & Oceans',
      'Geography: Mountains & Rivers',
      'Geography: Cities & Landmarks',
      'Geography: Flags of the World',
      'Geography: World Wonders',
    ],
  },
  {
    label: 'Science',
    subCategories: [
      'Science: General',
      'Science: Biology',
      'Science: Chemistry',
      'Science: Physics',
      'Science: Astronomy & Space',
      'Science: Geology',
      'Science: Inventions & Discoveries',
      'Science: Human Body & Medicine',
    ],
  },
  {
    label: 'Art & Literature',
    subCategories: [
      'Art & Literature: General',
      'Art & Literature: Art: Famous Paintings',
      'Art & Literature: Art: Sculptures',
      'Art & Literature: Art: Artists',
      'Art & Literature: Art: Art Movements',
      'Art & Literature: Literature: Genres',
      'Art & Literature: Literature: Authors',
      'Art & Literature: Literature: Literary Devices',
      'Art & Literature: Literature: Famous Books',
    ],
  },
  {
    label: 'Food & Drink',
    subCategories: [
      'Food & Drink: General',
      'Food & Drink: Cuisines of the World',
      'Food & Drink: Dishes & Ingredients',
      'Food & Drink: Beverages (Coffee, Tea, Alcoholic Drinks)',
      'Food & Drink: Desserts',
      'Food & Drink: Cooking & Culinary Terms',
    ],
  },
  {
    label: 'Animals',
    subCategories: [
      'Animals: General',
      'Animals: Mammals',
      'Animals: Birds',
      'Animals: Reptiles',
      'Animals: Amphibians',
      'Animals: Fish',
      'Animals: Insects & Arachnids',
      'Animals: Marine Life',
      'Animals: Domestic Animals (Cats, Dogs, Horses)',
      'Animals: Wild Animals',
      'Animals: Animal Behavior',
    ],
  },
  {
    label: 'Mythology',
    subCategories: [
      'Mythology: General',
      'Mythology: Greek Mythology',
      'Mythology: Roman Mythology',
      'Mythology: Norse Mythology',
      'Mythology: Egyptian Mythology',
      'Mythology: Mythical Creatures',
    ],
  },
  {
    label: 'Technology',
    subCategories: [
      'Technology: General',
      'Technology: Computers & Software',
      'Technology: Gadgets & Devices',
      'Technology: Programming Languages',
      'Technology: Internet & Web',
      'Technology: Artificial Intelligence',
      'Technology: Robotics',
    ],
  },
  {
    label: 'Current Events',
    subCategories: [
      'Current Events: General',
      'Current Events: News (Recent Headlines)',
      'Current Events: Politics (Recent Events)',
      'Current Events: Major Global Developments',
    ],
  },
  {
    label: 'Holidays',
    subCategories: [
      'Holidays: General',
      'Holidays: Christmas',
      'Holidays: Halloween',
      'Holidays: Thanksgiving',
      'Holidays: Valentine"s Day',
      'Holidays: Easter',
      'Holidays: Cultural Festivals',
    ],
  },
  {
    label: 'Language & Words',
    subCategories: [
      'Language & Words: General',
      'Language & Words: Vocabulary',
      'Language & Words: Etymology',
      'Language & Words: Grammar',
      'Language & Words: Spelling',
      'Language & Words: Foreign Words/Phrases',
    ],
  },
]

export default categories
